title: NAZOLASLIFE...
author: nazlicancelebi
email: nazlicancelebi@icloud.com
description: You'll see my coding world.

github_username:  nazlicancelebi 

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
